-- Generated from configs/bank/schema.json by scripts/load_mock_mysql.py --write-schema.
-- Synthetic source data only. Use the configured database; no DROP/TRUNCATE/ALTER.

CREATE TABLE IF NOT EXISTS `customer_tags` (
  `rowkey` VARCHAR(100) NULL COMMENT 'ROWKEY',
  `cust_ind` VARCHAR(100) NOT NULL COMMENT '客户唯一标志',
  `ecif_cust_id` VARCHAR(100) NULL COMMENT 'ECIF客户号',
  `cust_nm` VARCHAR(400) NULL COMMENT '客户姓名',
  `unify_credit_code` VARCHAR(50) NULL COMMENT '统一社会信用代码',
  `found_dt` VARCHAR(10) NULL COMMENT '成立日期',
  `survival_status` VARCHAR(100) NULL COMMENT '存续状态',
  `opscope` VARCHAR(6000) NULL COMMENT '经营范围',
  `cert_capt_amt` DECIMAL(26,8) NULL COMMENT '注册资金金额',
  `cert_capt_ccy` VARCHAR(20) NULL COMMENT '注册资金币种_三位字母',
  `org_capt_amt` DECIMAL(26,8) NULL COMMENT '实收资本金额',
  `org_capt_ccy` VARCHAR(20) NULL COMMENT '实收资本币种',
  `hold_type` VARCHAR(20) NULL COMMENT '企业出资人经济成分代码',
  `corp_econ_type` VARCHAR(20) NULL COMMENT '企业经济类型',
  `four_commis_corp_scale` VARCHAR(100) NULL COMMENT '企业规模（四部委）',
  `cert_province` VARCHAR(100) NULL COMMENT '注册地省代码',
  `cert_city` VARCHAR(100) NULL COMMENT '注册地城市代码',
  `cert_district` VARCHAR(100) NULL COMMENT '注册地区县代码',
  `busin_addr` VARCHAR(400) NULL COMMENT '实际经营地址',
  `mec_num` INT NULL COMMENT '从业人数',
  `industry_cd` VARCHAR(20) NULL COMMENT '行业门类',
  `industry_big_cd` VARCHAR(20) NULL COMMENT '行业分类大类',
  `industry_mid_cd` VARCHAR(20) NULL COMMENT '行业分类中类',
  `industry_sml_cd` VARCHAR(20) NULL COMMENT '行业分类小类',
  `oprt_cust_ind` VARCHAR(1) NULL COMMENT '可经营客户标志',
  `scient_corp_ind` VARCHAR(20) NULL COMMENT '科技型企业标志',
  `soe_ind` VARCHAR(1) NULL COMMENT '国资企业标志',
  `poe_ind` VARCHAR(1) NULL COMMENT '民营企业标志',
  `cb_poe_ind` VARCHAR(1) NULL COMMENT '民营企业（跨境）标志',
  `icpe_ind` VARCHAR(1) NULL COMMENT '民营企业（个体工商户）标志',
  `gov_com_fin_ind` VARCHAR(1) NULL COMMENT '政府委办（财政）标志',
  `gov_com_chs_ind` VARCHAR(1) NULL COMMENT '政府委办（医保）标志',
  `gov_com_other_ind` VARCHAR(1) NULL COMMENT '政府委办（其他）标志',
  `ngo_ind` VARCHAR(1) NULL COMMENT '社会团体标志',
  `re_comp_ind` VARCHAR(1) NULL COMMENT '房地产企业标志',
  `fl_ind` VARCHAR(1) NULL COMMENT '融资租赁标志',
  `mainten_fund_ind` VARCHAR(1) NULL COMMENT '维修资金标志',
  `legal_rep_nm` VARCHAR(400) NULL COMMENT '法人姓名',
  `legal_rep_cust_id` VARCHAR(100) NULL COMMENT '法人客户编号',
  `act_ctrl_psn_nm` VARCHAR(400) NULL COMMENT '实际控制人姓名',
  `act_ctrl_psn_cust_id` VARCHAR(100) NULL COMMENT '实际控制人客户编号',
  `vol_manager_id` VARCHAR(100) NULL COMMENT '管护权客户经理编号（自动）',
  `vol_manager_org_id` VARCHAR(100) NULL COMMENT '管护权客户经理所属机构（自动）',
  `manu_manager_id` VARCHAR(100) NULL COMMENT '管护权客户经理编号（手动）',
  `manu_manager_org_id` VARCHAR(100) NULL COMMENT '管护权客户经理所属机构（手动）',
  `pyrl_sign_ind` VARCHAR(1) NULL COMMENT '代发工资签约标志',
  `rplymt_tax_sign_ind` VARCHAR(1) NULL COMMENT '代缴税费签约标志',
  `itnst_sign_ind` VARCHAR(1) NULL COMMENT '国际结算签约标志',
  `corp_ebnkg_sign_ind` VARCHAR(1) NULL COMMENT '企业网银签约标志',
  `mb_sign_ind` VARCHAR(1) NULL COMMENT '手机银行签约标志',
  `snd_bl_sign_ind` VARCHAR(1) NULL COMMENT '二代票签约客户标志',
  `snd_bl_cust_sign_ind` VARCHAR(10) NULL COMMENT '代发工资签约日期',
  `pyrl_sign_dt` VARCHAR(10) NULL COMMENT '代缴税费签约日期',
  `corp_ebnkg_sign_dt` VARCHAR(10) NULL COMMENT '企业网银签约日期',
  `mb_sign_dt` VARCHAR(10) NULL COMMENT '手机银行签约日期',
  `snd_bl_sign_dt` VARCHAR(10) NULL COMMENT '二代票签约日期',
  `agt_cnt_12m` INT NULL COMMENT '近12月代发笔数',
  `agt_amt_12m` DECIMAL(26,8) NULL COMMENT '近12月代发金额',
  `agt_num_12m` INT NULL COMMENT '近12月代发人数',
  `agt_vld_ind_12m` VARCHAR(1) NULL COMMENT '近12月有效代发客户标志',
  `corp_ebnkg_trans_y_ind` VARCHAR(1) NULL COMMENT '企业网银年交易标志',
  `corp_mb_trans_y_ind` VARCHAR(1) NULL COMMENT '企业手机银行年交易标志',
  `pyst_cust_y_ind` VARCHAR(1) NULL COMMENT '当年票据支付结算客户标志',
  `swap_corp_cust_ind` VARCHAR(1) NULL COMMENT '外汇企业客户标志',
  `cash_cst_ind` VARCHAR(1) NULL COMMENT '现金管理客户标志',
  `sk_cust_ind` VARCHAR(1) NULL COMMENT '司库客户标志',
  `forex_cust_y_ind` VARCHAR(1) NULL COMMENT '当年结售汇客户标志',
  `open_acct_dt` VARCHAR(10) NULL COMMENT '最早开户日期',
  `lvl1_cust_ind` VARCHAR(1) NULL COMMENT '一类户客户标志',
  `bsc_dep_acct_ind` VARCHAR(1) NULL COMMENT '基本户客户标志',
  `manu_settle_amt` DECIMAL(26,8) NULL COMMENT '近12月主动结算金额',
  `manu_settle_amt_avg_cnt` INT NULL COMMENT '近12个月月均主动结算笔数',
  `zero_dep_cust_ind` VARCHAR(1) NULL COMMENT '零存款客户标志',
  `genal_cust_ind` VARCHAR(1) NULL COMMENT '一般客户标志',
  `ptntl_cst_ind` VARCHAR(1) NULL COMMENT '潜力客户标志',
  `val_cust_ind` VARCHAR(1) NULL COMMENT '价值客户标志',
  `mediun_cust_ind` VARCHAR(1) NULL COMMENT '中型客户标志',
  `key_cust_ind` VARCHAR(1) NULL COMMENT '重点客户标志',
  `exchg_c_bal` DECIMAL(26,8) NULL COMMENT '本外币对公存款余额',
  `exchg_c_bal_yavg` DECIMAL(26,8) NULL COMMENT '本外币对公存款年日均',
  `c_exchg_cny_12m_yaug` DECIMAL(26,8) NULL COMMENT '近12月人民币普通企业存款年日均',
  `exchg_cny_dmd_12m_yaug` DECIMAL(26,8) NULL COMMENT '近12月人民币活期存款年日均',
  `crg_cst_ind` VARCHAR(1) NULL COMMENT '授信客户标志',
  `project_loan_cust_ind` VARCHAR(1) NULL COMMENT '科创贷款客户标志',
  `green_loan_cust_ind` VARCHAR(1) NULL COMMENT '绿色贷款客户标志',
  `ph_loan_cust_ind` VARCHAR(1) NULL COMMENT '普惠贷款客户标志',
  `manufacture_indu_loan_cust_ind` VARCHAR(1) NULL COMMENT '制造业贷款客户标志',
  `bill_fin_cust_ind` VARCHAR(1) NULL COMMENT '票据融资客户标志',
  `supply_core_cust_ind` VARCHAR(1) NULL COMMENT '供应链核心企业标志',
  `supply_chain_cust_ind` VARCHAR(1) NULL COMMENT '供应链链条企业标志',
  `our_bank_credit_lmt` DECIMAL(26,8) NULL COMMENT '我行授信额度',
  `our_bank_credit_bal` DECIMAL(26,8) NULL COMMENT '我行授信余额',
  `our_bank_usd_lmt` DECIMAL(26,8) NULL COMMENT '我行已用额度',
  `our_bank_avl_lmt` DECIMAL(26,8) NULL COMMENT '我行可用额度',
  `exchg_c_loan_bal` DECIMAL(26,8) NULL COMMENT '本外币对公贷款余额',
  `exchg_c_loan_yavg` DECIMAL(26,8) NULL COMMENT '本外币对公贷款年日均',
  `cny_c_loan_bal` DECIMAL(26,8) NULL COMMENT '人民币一般对公贷款余额',
  `amt_mid_i` DECIMAL(26,8) NULL COMMENT '中间业务收入',
  `eva` DECIMAL(26,8) NULL COMMENT 'EVA',
  `corp_report_dt` VARCHAR(10) NULL COMMENT '企业最新征信报告时间',
  `report_crdt_amt` DECIMAL(26,8) NULL COMMENT '最新征信报告总授信额度',
  `report_crdt_bal` DECIMAL(26,8) NULL COMMENT '最新征信报告总授信余额',
  `report_crdt_our_bank_amt` DECIMAL(26,8) NULL COMMENT '最新征信报告我行授信额度',
  `report_crdt_our_bank_bal` DECIMAL(26,8) NULL COMMENT '最新征信报告我行授信余额',
  `abnormity_cust_ind` VARCHAR(1) NULL COMMENT '经营状态异常客户',
  `risk_cust_ind` VARCHAR(1) NULL COMMENT '预警客户标志',
  `aml_high_lvl_cust_ind` VARCHAR(1) NULL COMMENT '反洗钱较高或高等级客户',
  `wire_fraud_risk_ind` VARCHAR(1) NULL COMMENT '电诈新型违法犯罪风险标志',
  `veason_cust_ind` VARCHAR(1) NULL COMMENT '久悬客户标志',
  `sleep_cust_ind` VARCHAR(1) NULL COMMENT '休眠客户标志',
  `loan_overdue_cust_ind` VARCHAR(1) NULL COMMENT '贷款逾期客户标志',
  `badloan_cust_ind` VARCHAR(1) NULL COMMENT '不良贷款客户标志',
  `hhnw_tech_entp_ind` VARCHAR(1) NULL COMMENT '高新技术企业标志',
  `spldnctgdtin_sme_ind` VARCHAR(1) NULL COMMENT '专精特新中小企业标志',
  `spldnctgdtin_shpe_ind` VARCHAR(1) NULL COMMENT '专精特新小巨人称号标志',
  `st_tp_sme_ind` VARCHAR(1) NULL COMMENT '科技型中小企业客户标志',
  `invt_tp_sme_ind` VARCHAR(1) NULL COMMENT '创新型中小企业标志',
  `ctytechinvtdmtentp_ind` VARCHAR(1) NULL COMMENT '国家技术创新示范企业标志',
  `mecidyidvchpnentp_ind` VARCHAR(1) NULL COMMENT '制造业单项冠军企业标志',
  `latest_fnc_round` VARCHAR(10) NULL COMMENT '最新融资轮次',
  `latest_round_fnc_amt` DECIMAL(26,8) NULL COMMENT '最新轮次融资金额',
  `latest_round_fnc_cny` VARCHAR(10) NULL COMMENT '最新轮次融资币种',
  `latest_round_fnc_inv` VARCHAR(400) NULL COMMENT '最新融资轮次投资方',
  `ipo_ind` VARCHAR(1) NULL COMMENT '上市标志',
  `starr_market_ind` VARCHAR(1) NULL COMMENT '科创板上市标志',
  `chinext_ind` VARCHAR(1) NULL COMMENT '创业板上市标志',
  `neeq_ind` VARCHAR(1) NULL COMMENT '新三板上市标志',
  `debt_issu_corp_ind` VARCHAR(1) NULL COMMENT '发债企业标志',
  `ues_rplymt_tax_y_ind` VARCHAR(1) NULL COMMENT '当年使用代缴税费标志',
  `SH_SCI_RNG` VARCHAR(400) NULL COMMENT '沪科积分区间',
  `SCIENT_REVOKE_12M_IND` VARCHAR(1) NULL COMMENT '近1年科技资质被撤销标志',
  `SCIENT_COUNTERFEIT_3Y_IND` VARCHAR(1) NULL COMMENT '近3年科技资质疑似包装标志',
  `SCIENT_DECLINE_LVL_3Y_IND` VARCHAR(1) NULL COMMENT '近3年科技资质等级下降标志',
  `NO_SCI_TECH_ACHI_2Y_IND` VARCHAR(1) NULL COMMENT '近2年无科技成果产出标志',
  `SCI_TECH_RANK_TAIL_2Y_IND` VARCHAR(1) NULL COMMENT '近2年科技力在同省同产业排名处于尾部标志',
  `RESE_DEV_PAT_LOW_2Y_IND` VARCHAR(1) NULL COMMENT '近2年独立研发专利占比低标志',
  `HIGH_VAL_PAT_RET_0_2Y_IND` VARCHAR(1) NULL COMMENT '近2年高价值专利降为0标志',
  `PAT_LAW_BINVA_3Y_IND` VARCHAR(1) NULL COMMENT '近3年专利涉诉被无效标志',
  `CST_MGRP_ID` VARCHAR(100) NULL COMMENT '所属集团编号',
  `CST_MGRP_NM` VARCHAR(200) NULL COMMENT '所属集团名称',
  `SETL_ACTV_ACCT_IND` VARCHAR(1) NULL COMMENT '结算活跃户标志',
  `MRAQ_LOAN_CUST_IND` VARCHAR(1) NULL COMMENT '并购贷款客户标志',
  `MANU_SETTLE_AMT_MON_NUM` INT NULL COMMENT '近12个月主动结算月份数',
  `PYRL_MON_NUM_12M` INT NULL COMMENT '近12个月代发月份数',
  `PYRL_AMT_M` DECIMAL(26,8) NULL COMMENT '当月代发金额',
  `CFM_CRG_PCT` DECIMAL(26,8) NULL COMMENT '我行授信占比',
  `NUM_PYRL_AMT_12M_AVG` DECIMAL(26,8) NULL COMMENT '近12个月笔均代发金额',
  `LATEST_PYRL_DT` VARCHAR(10) NULL COMMENT '最近一次代发日期',
  `UNION_MEC_NUM` INT NULL COMMENT '从业人数（合并）',
  `UES_RPLYMT_TAX_M_IND` VARCHAR(1) NULL COMMENT '当月使用代缴税费标志',
  `CORP_EBNKG_M_IND` VARCHAR(1) NULL COMMENT '当月使用企业网银标志',
  `CORP_MB_M_IND` VARCHAR(1) NULL COMMENT '当月使用企业手机银行标志',
  `CUST_STATUS` VARCHAR(20) NULL COMMENT '客户状态',
  `IDYCMRC_CAN_IND` VARCHAR(1) NULL COMMENT '工商注销客户标志',
  `dt` VARCHAR(8) NULL COMMENT '数据日期',
  PRIMARY KEY (`cust_ind`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin COMMENT='合成客户标签快照；来源 CCM_C_CUST_FLAG_INFO';

CREATE TABLE IF NOT EXISTS `customer_journey_events` (
  `DT` VARCHAR(8) NOT NULL COMMENT '日期分区',
  `ROWKEY` VARCHAR(200) NOT NULL COMMENT '技术主键',
  `EVT_CLASS` VARCHAR(3) NULL COMMENT '事件大类',
  `EVT_TYPE` VARCHAR(20) NULL COMMENT '事件类型',
  `CUST_ID` VARCHAR(50) NULL COMMENT '客户编号',
  `OCCUR_DT` VARCHAR(8) NOT NULL COMMENT '发生日期',
  `KEY_FLAG` VARCHAR(1) NULL COMMENT '是否重点事件',
  `PROPERTIES` LONGTEXT NULL COMMENT '事件属性；JSON 原文，保留十进制数精度',
  PRIMARY KEY (`DT`, `ROWKEY`),
  KEY `idx_customer_date` (`CUST_ID`, `OCCUR_DT`),
  KEY `idx_event_type_date` (`EVT_TYPE`, `OCCUR_DT`),
  CHECK (`PROPERTIES` IS NULL OR (JSON_VALID(`PROPERTIES`) AND JSON_TYPE(`PROPERTIES`) = 'OBJECT'))
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin COMMENT='合成客户旅程事件；来源 E_CRM_C_CUST_TOUR_EVT_SUM';
